### ISSUE TITLE
Runtime environment

### ISSUE THREAD

**Issue by Jason-xy** [mac999/scan_to_bim_pipeline#1]
Thank you for your efforts, this is a valuable project through the demo! When I tried to build the environment by following the steps in readme.md,  it didn't go well. Is there any pre-built container environment that can execute demos? Thanks for your reply!

**Comment by mac999** [comment]
Thanks for your interests. I'll prepare the pre-built container, but if you can upload your error logs, it's helpful to solve the issues.
